### ISSUE TITLE
Change exe target to include web package content

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#17]

**Comment by mhosken** [comment]
Fixed in 3e576a8

**Comment by bobh0303** [comment]
As in #18, the generated woff file is not present.

**Comment by mhosken** [comment]
Where should the resulting .woff file be put? Is it just considered part of the web/ documentation?

**Comment by devosb** [comment]
Our Font Build Targets and Structure says to put the .woff file in web/
