### ISSUE TITLE
Change zip target to include web package content

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#18]

**Comment by mhosken** [comment]
fixed in 3e576a8

**Comment by bobh0303** [comment]
Close, but not yet complete.

My wscript specifies `DOCDIR=["documentation", "web"]` and both the `web` and `documentation` folders are included in the zip -- so far so good.

However the `web` folder does not include the generated woff files. I think a wscript construct may be needed to identify where the woff files should go in zips, etc.)

**Comment by mhosken** [comment]
Normally the location of the target governs where it ends up in the zip. Do we want to follow that here? i.e.
 require something like:

````
woff = woff('web/target.woff'),
````

**Comment by bobh0303** [comment]
Verified correct behavior.
