### ISSUE TITLE
Change srcdist target to build .tar.xz (with no '-source' suffix) including web package content

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#19]

**Comment by n7s** [comment]
Our current python module choice does not support the .xz format. Maybe we can consider .bz2 instead.

**Comment by devosb** [comment]
The .xz format is now used, by calling the external xz command. I used the default compression levels for xz. On a test tarball, the -6 (the default) and -9 compression options produced the same size file, and --extreme was 10% bigger than without --extreme.

**Comment by n7s** [comment]
Great, I guess the external subprocess is a good option too. It looks xz-utils is already part of the core set of packages so no need for an explicit dependency.

**Comment by devosb** [comment]
In the past I have seen differences in the number of packages between the base image of Ubuntu as provided by Canonical and the base image of Ubuntu as provided by Docker. Other VM systems may have yet another base set of packages. I would suggest adding xz as a dependency.

**Comment by n7s** [comment]
Ah yes, good thinking. An explicit dependency will not do any harm but could catch the cases where other VM setups have other deps. I've added the dep.

**Comment by n7s** [comment]
We still need to gather css, html and woff files for release.

**Comment by n7s** [comment]
There is now a explicite rule to grab the contents of web/

**Comment by n7s** [comment]
the srcdistcheck target needs to be updated after the change to xz

**Comment by devosb** [comment]
Commit b88b9da7c12c140687770295f77caa8ef853f9c8 added xz functionality, but broke the srcdistcheck target that @n7s found. The srcdistcheck target was just fixed in commit 7a9f5fe0650b87ef582810b234fe81bc02c0cbae. The need to include web content will be handled in issue #30.
