### ISSUE TITLE
fix handling VCS development version numbering

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#21]

**Comment by mhosken** [comment]
Issue #7 fixed broken .exe generation. For specific actions that fail if a VERSION contains development information, please raise an issue against each one. This issue is about how best to handle wscript author interaction with version numbers.

Do we want VERSION to automatically have -dev-{vcscommitid} appended to it unless building release? Do we want to be able to block that? Do we assume if a .git exists (or whatever) that users want this automatic behaviour?

**Comment by n7s** [comment]
I'd say -dev-{vcscommitid} by default in VERSION and explicit release -r removes it. 
I'd assume a font project is being developed in a VCS repo anyway so tracking the current state of that repo in a suffix tag in the generated artifacts is a good idea.

**Comment by mhosken** [comment]
There are a number of interplays on this. The whole question of where the VERSION comes from and what we do to is subsequently and what all may use it. For example, we could say: just set the VERSION to be a simple number and smith will automatically add the -dev- stuff. But then another application won't get that if they just use VERSION. Equally, we might say, but we want the VERSION to come from a font. And we don't particular want to have special functions in there like (getufofontversion() or getvcsversion()) for the reason of not working for apps that just want to read a wscript.

How about adding FULLVERSION which is default derived from VERSION? That deals with the -dev- question. That just leaves the getting VERSION from a font, question.

If we say VERSION=UFOVersion('source/UFO-Regular.ufo') then that solves the problem for smith. But if we want to make wscript executable by other applications then we would want to hide that and bury that in the smith only section. That's probably OK.

**Comment by jvgaultney** [comment]
> But if we want to make wscript executable by other applications...
What in the world? So what applications to you have in mind?
You're adding far too much unnecessary complexity, and every bit of cruft like that will only make long-term maintenance more difficult.

**Comment by mhosken** [comment]
We now have two new controlling package variables: BUILDLABEL and BUILDFORMAT. BUILDLABEL contains things like "beta2" and defaults to blank. BUILDFORMAT controls the format of the vcs generated part of BUILDVERSION. It defaults to dev-{vcsshar:6}{vcsmodified}, which gives something like dev-ab102gM. BUILDVERSION is then defaults to be BUILDLABEL+" " plus the generated vcs component. Clearly, if this is a release build, BUILDVERSION is set to empty. VERSION is still used as the primary version number and should x.yyy.
