### ISSUE TITLE
Consider renaming targets

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#22]

**Comment by mhosken** [comment]
Specifically which ones?

**Comment by n7s** [comment]
probably still under discussion but as a start I'd say:
* srcdist -> tarball
* release (chaining zip and tarball in -r release mode)

**Comment by n7s** [comment]
configure -> conf   ?

Although with bash_completion (which I'll update accordingly) it shouldn't be too slow to type these targets anyway.

I guess overall we just want things that make sense to new users and don't require insider knowledge. 
Should we consider providing shorter aliases to the longer commands maybe? Or is that too much?

**Comment by jvgaultney** [comment]
No need to change configure>conf. It's not any clearer, so it's unnecessary.

**Comment by mhosken** [comment]
bear in mind that __changing__ a target (as opposed to adding one) is a backward breaking changing, so we should do all such backward breaking very close together.

**Comment by jvgaultney** [comment]
Well would making 'smith tarball' necessarily deprecate 'smith srcdist'?
And 'smith release' is new, so we're not talking about any changes that would break things

**Comment by mhosken** [comment]
Any others?

**Comment by mhosken** [comment]
We want to use tarball as the target to create the production tarball which consists of the same contents as the zip target but with linux line endings. On this basis, there are no modifications to existing targets and how they are named. Closing.
