### ISSUE TITLE
Remove FontForge dependency in main build chain

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#28]

**Comment by mhosken** [comment]
The aim here is to remove fontforge from the ufo source build chain. Currently fontforge is used for the following activities for a ufo project. These would have to all be retooled:

- compile ufo to ttf
- compile fea to OT into a ttf

Bear in mind that fontforge will still be needed for sfd based build chains. But we can remove it as a required dependency if we address the above.

**Comment by bobh0303** [comment]
Compile ufo to ttf is simple using AW's `ufo2ttf`.
Compile fea to OT is simple using `fonttools feaLib`

**Comment by mhosken** [comment]
testing branch removeff available

**Comment by nrsiward** [comment]
The removeff branch was merged. A new smith is available to deploy to font teams using provision.sh.
