### ISSUE TITLE
making PDFs with OpenType

### ISSUE THREAD

**Issue by devosb** [silnrsi/smith#3]
Section 4.1 OpenType of the smith manual says you can write opentype = internal() to indicate a font has OpenType tables, and should used OpenType rendering for making PDFs. It also says that specifying the sfd_master parameter also indicates OpenType. IIUC, if sfd_master is set, opentype = internal() is not needed. But when I tried this on https://github.com/nlci/knda-font-badami I get an error when running smith pdfs

AttributeError: 'Font' object has no attribute 'opentype'

**Comment by mhosken** [comment]
That's a bug in the manual. I think it was wishful thinking, but I don't think that it adds value to make sfd_master do a magic opentype=internal().

**Comment by mhosken** [comment]
Implications removed from docs
