### ISSUE TITLE
Change srcdist target to include web package content 

### ISSUE THREAD

**Issue by devosb** [silnrsi/smith#30]
I don't think the recent change @n7s made in  b07569fc30bdac8cd927f7aba7fed6c7adde2f02 to archive this works. At least not that I can reproduce. I have (in wscript) both

woff = woff('web/' + tag + f + '-' + sn.replace(' ', '') + '.woff'),

To place .woff files in a web/ directory and

DOCDIR=["web"]

**Comment by mhosken** [comment]
This is being covered by issue #18.

**Comment by devosb** [comment]
Issue #18 does not solve this issue. Issue #31 is needed more than this issue. For this issue, a web server admin could copy the needed woff files out of a zip file to whatever directory their web server software requires.

**Comment by devosb** [comment]
This issue will be handled with code changes need for issue #31.
