### ISSUE TITLE
Change srcdist target to include built ttf files

### ISSUE THREAD

**Issue by devosb** [silnrsi/smith#31]
This is needed so the resulting tarball can serve as a source tarball for Debian packaging.

**Comment by n7s** [comment]
Mmm. If you're packaging pre-built ttf files, use the zip. If you're rebuilding from source (self-hosting full buildpath) use the source tarball?

**Comment by mhosken** [comment]
I think what Bobby wants is the srcdist to have the built targets so that it can be used as the basis for a debian package which either rebuilds or uses built targets. Anyway, the code is there to add them in the results (or whatever the build directory is).

**Comment by devosb** [comment]
After further discussion, Debian packages will be built (for now) from a tar file that does not include the font source. This new tar file will have the same content as the zip file that smith produces. Therefore, the work on this command can be reverted
* No need to trigger a build before running srcdist
* No need to include built files (.ttf and .woff)
* vcs dot files (such as .gitattributes and .gitignore) can be excluded from the tar file

**Comment by n7s** [comment]
.git* (or .hg* or even *.svn) should be removed.

**Comment by mhosken** [comment]
Still triggers a build, but that's a bug that we can fix later

**Comment by bobh0303** [comment]
A thought: since it is all the same as the zip, why not just build it as a by-product of the zip target?  Just do it before the line-ending change, then do the line-ending change and make the zip. This will guarantee there is no build between and the contents of the two packages are, indeed, the same (other than line endings).

**Comment by mhosken** [comment]
No, this is the source distribution, which we aren't using in our workflow now. So it's a minimal issue that it still requires a build. The reasoning is deep and something to do with contexts and font tests which I could spend time on, but will only do so if the need arises.

**Comment by mhosken** [comment]
Keep them separate. No action needed.
