### ISSUE TITLE
Target to provide checksums and signature files alongside artifacts 

### ISSUE THREAD

**Issue by n7s** [silnrsi/smith#35]
Debian (and possibly) others would like to have checksums (probably SHA512SUM) and cryptographic signatures (probably GPG .asc or .sig files) for released artifacts.  We should investigate how feasible it is for smith to generate those for us.

**Comment by devosb** [comment]
To me it seems like the big question is do you use a gpg key with a passphrase? If you use a passphrase, then smith cannot generate a cryptographic signatures, as it would not be able to access the key. If there is no passphrase, if someone compromises the server they could gain access to the key and sign (maliciously) any files they modify.

**Comment by n7s** [comment]
Yes, we will have to assess the threat model. There is precedent and also documentation for doing this AFAICT.

**Comment by n7s** [comment]
First attempt in 5946d9f

**Comment by bobh0303** [comment]
Smith has been generating a checksum for quite a while now.
