### ISSUE TITLE
should provision.sh include --with-new-pkgs ?

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#42]
When I re-provision my VM, I often get this kind of thing in the output:
```
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Calculating upgrade...
==> default: The following packages have been kept back:
==> default:   linux-headers-generic linux-headers-virtual linux-image-virtual
==> default:   linux-virtual
==> default: 0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```
In this case it was a few system packages, but more often than not the "not upgraded" list has included smith and friends.

I'm wondering if, in `vm-install/provision.sh`, the `apt-get upgrade` command should include the `--with-new-pkgs` option which is documented:
>--with-new-pkgs
>  Allow installing new packages when used in conjunction with upgrade. This is useful if the update of a installed package requires new dependencies to be installed. Instead of holding the package back upgrade will upgrade the package and install the new dependencies. Note that upgrade with this option will never remove packages, only allow adding new ones.

Adding that, in my case, resulted in the four packages being upgraded (after dependencies installed):
```
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Calculating upgrade...
==> default: The following NEW packages will be installed:
==> default:   linux-headers-4.4.0-87 linux-headers-4.4.0-87-generic
==> default:   linux-image-4.4.0-87-generic
==> default: The following packages will be upgraded:
==> default:   linux-headers-generic linux-headers-virtual linux-image-virtual
==> default:   linux-virtual
==> default: 4 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 32.7 MB of archives.
==> default: After this operation, 145 MB of additional disk space will be used.
```

**Comment by devosb** [comment]
An `apt-get upgrade` command also exists in `Vagrantfile`. I suspect both places should have this new option, but have not tested this.

**Comment by n7s** [comment]
The profiles have been updated.
