### ISSUE TITLE
need preflightg added to dot.gitattributes

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#46]
https://github.com/silnrsi/smith/blob/0b9e2de342247bc4c4f9bdb03edc45df6319e0ea/smithlib/dot.gitattributes#L42

Either add explicitly:
```
preflight text eol=lf
preflightg text eol=lf
```
or glob:
```
preflight* text eol=lf
```
I don't know which is preferred.

**Comment by mhosken** [comment]
Let's go with preflightg for now. If more appear, we can change them to * then.

**Comment by bobh0303** [comment]
Did you make the change before closing the issue?
