### ISSUE TITLE
When doing multiple runs of grcompiler, gdlerr.txt gets overwritten 

### ISSUE THREAD

**Issue by n7s** [silnrsi/smith#47]
Grcompiler defaults to gdlerr.txt for error output. Doing multiple runs (like in a CI) currently causes information loss because that file gets overwritten by the last output.  We need a way to keep separate files per run.

See https://github.com/silnrsi/grcompiler/issues/2 for a new parameter in grcompiler 

Alternatively we do file renames (redirects?) in smith directly every time: maybe something like $FooFont-$weight-gdl-errors.txt

**Comment by mhosken** [comment]
Waiting on a release of grcompiler with the added CLI

**Comment by bobh0303** [comment]
Fixed. Further discussion about in-tree and out-of-tree in #52
