### ISSUE TITLE
Support alias and config files for TypeTuner 

### ISSUE THREAD

**Issue by nrsiward** [silnrsi/smith#48]
Add a TypeTuner class, `tt`, which can be passed as the value of the `typetuner` parameter for the `font` class. For example:

```
font( target=..., 
    typetuner=tt('features.xml', aliases='fea_aliases.csv', config = [config.xml]), 
    ... )
```
The presence of the tt object will:
1. cause the alias file (e.g. fea_aliases.csv) to be generated when the fea is compiled by psfbuildfea
1. cause TypeTuner to be ran such that the features xml file is added to the built font with the aliases and config files passed as parameters

See [Font Workflow 167 TypeTuner](https://docs.google.com/document/d/1FFfrYhO5ca2TQX9mxu1oj4tE6HdnKQSnb_s3lRZIkyo/edit#) for details.

**Comment by mhosken** [comment]
Waiting on CLI changes to typetuner. When those are resolved, return here and indicate that this bug is ready to go.

**Comment by bobh0303** [comment]
With the addition of `tuneraliases` command to pysilfont and additional logic in smith (f512693e and 8b912e7a), we have support for TypeTuner workflow.  To use, add `typetuner` parameter to `designspace()` function in wscript:
```
typetuner = typetuner('source/feat_all.xml'),
```
Opentype and Graphite aliases for the compiled font will be merged with any existing aliases in the `feat_all.xml`.

**Comment by mhosken** [comment]
You also need a `mapfile` parameter to your opentype fea() object.
