### ISSUE TITLE
smithlib/dot.gitattributes mystery

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#5]
What is this: 

```
 # Set the default behavior, we expect Windows users to use a VM for now 
 text eol=lf
```

code in the suggested .gitattributes file intended to do? What I can see in [gitattributes documentation](https://git-scm.com/docs/gitattributes) suggests that this will set the line-ending for a single file called "text", but that is not what the comment suggests.

**Comment by mhosken** [comment]
That should read:

````
[attr]text eol=lf
````

and is designed to set the eol property on all text files.

**Comment by bobh0303** [comment]
That would make more sense -- and match the comment.
