### ISSUE TITLE
designspace deferred string replacements

### ISSUE THREAD

**Issue by mhosken** [silnrsi/smith#51]
In supporting the designspace function, I notice that it is really hard to modify the various magic strings that come back from the designspace procesing. One can't simply modify the string, since the string is lazily and late evaluated. The problem arises because so many of the variables from the designspace instance can have spaces in them.

So I've added a str_replace() that gets deferred so that the inside values are expanded. Currently it just calls str.replace. I'm wondering if it needs to call re.sub instead. Which would folk prefer?
or maybe we need some kind of deferred_eval.

I think `defer_map(lambda x:x.replace(' ', '-'), '${NAME}.ttf')` for the target attribute is a mouthful too much. `str_replace('${NAME}.ttf', ' ', '-')` is bad enough (and probably too bad too). Other alternatives include: `'${NAME/ /-}.ttf'` ala bash or `'${NAME_D}.ttf'` as in a magic set of variables with _D suffix for dash.

**Comment by jvgaultney** [comment]
Is there an assumption on which Axes would be supported? Probably should include the common axes (AXIS_WEIGHT, AXIS_WIDTH, AXIS_CUSTOM).

**Comment by bobh0303** [comment]
N: or D: prefix?   Propose DS: instead.

**Comment by mhosken** [comment]
AXIS_ whatever is listed as a dimension in the location element of the instance (or else whatever is in the axis/@name for all the axes/axis elements). So whatever you put in the designspace file is what you can ask for.
I can go with DS: prefix.
