### ISSUE TITLE
XeTeX from TeXLive2018

### ISSUE THREAD

**Issue by LornaSIL** [silnrsi/smith#53]
Since there is now a TeXLive2018 from April 28, 2018 it would be useful to update XeTeX.
https://www.tug.org/texlive/

**Comment by n7s** [comment]
The VM profile are now using TeXLive2018 which includes a newer version of XeTeX (along with the CI). 
Specifically XeTeX 3.14159265-2.6-0.99999 (TeX Live 2019/dev/Debian).
