### ISSUE TITLE
Split 'smith sile' into separate commands to process .sil and .ftml files

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/smith#61]
At the moment 'smith sile' will process all .sil and .ftml files through SILE. However it would be useful to be able to process the two types of files separately, so that .sil files could be processed without triggering the sometimes more lengthy .ftml collection. in some projects (like Gentium) there are hundreds of pages of .ftml, which can take considerable time.

Please split the command so that 'smith sile' processes only .sil files and 'smith sileftml' processes only .ftml files.

**Comment by devosb** [comment]
Closed in https://github.com/silnrsi/smith/commit/ac95e9266a297ebb6883e42776b937f01f0dabdf

Note that the output directory has changed for PDFs from FTML files to `sileftml`.
