### ISSUE TITLE
use psfwoffit by default -- but with new options

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#62]
As a result of FontTech discussions we've concluded:

1) Most of our projects should, for now anyway, be producing both woff and woff2, though some projects may need to produce just one (woff _or_ woff2) rather than both. 
2) It would be reasonable to start using psfwoffit in all cases.
3) Simpler is better (i.e., it would be nice if wscript authors didn't have to supply cmd attribute to woff()

We didn't discuss this but I think:

4) Untouched projects should continue to generate just the woff, making it a conscious decision on the part of wscript authors to generate woff2 (or woff _and_ woff2).

Implementation is flexible. 

One suggestion was to clone woff() into a woff2() object so it would be a matter of including either or both in the wscript. This would introduce a slight inefficiency unless smith could figure out how to merge these two into a single run of psfwoffit, but the tool is relatively fast so this probably won't be noticed.

Personally I'd prefer a single woff() object that could do either/both, but I'm not sure whether smith can handle a process that generates 1 or 2 outputs. Possible implemention: to woff() add a `type` attribute which is a list, e.g.:
* `woff(... , type=('woff',), ...)`   # default 
* `woff(... , type=('woff2',), ...)`
* `woff(... , type=('woff', 'woff2'), ...)`

**Comment by mhosken** [comment]
I propose the following:
- We upgrade the `woff` function/class to use psfwoffit
- We default the type to `('woff', 'woff2')` for now, but the default may change to `'woff2'` (that way there is no need for an extra comma in a single item tuple.
- The passed filename will have its extension removed and replaced with the appropriate `woff` or `woff2`.

**Comment by bobh0303** [comment]
Fixed by commits f54ba5d8 through 248b38aa
