### ISSUE TITLE
installGraphiteFromSource is incomplete

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#64]
Before the initial `vagrant up` of a `focal` VM, if I modify `provision.sh` to enable: 
```
# set to True to compile Graphite and harfbuzz from source (including tracing):
graphiteFromSource=True
```
then the resulting machine doesn't include `hb-shape` or `hb-view`:
```
vagrant@smith-focal:~$ hb-shape
Command 'hb-shape' not found, but can be installed with:
apt install libharfbuzz-bin
Please ask your administrator.
```
After executing `sudo apt install libharfbuzz-bin` the commands were, indeed, present.

It would be good if we could make sure this package is installed from `provision.sh`.

**Comment by n7s** [comment]
This conditional has been added a while ago.
