### ISSUE TITLE
Why does Master need to be in the source family name?

### ISSUE THREAD

**Issue by devosb** [silnrsi/smith#69]
[Namdhinggo](https://github.com/silnrsi/font-namdhinggo) produces a range of weights Regular to ExtraBold instead of multiple RIBBI families. The text _Master_ was removed from the UFOs as it is not needed, and the removal makes it easier to build the project with `fontmake`. Master was also going to be removed from the Designspace file, however, it seems to be needed in the `familyname` attribute of the `source` tag (lines [22](https://github.com/silnrsi/font-namdhinggo/blob/master/source/Namdhinggo.designspace#L22) and [33](https://github.com/silnrsi/font-namdhinggo/blob/master/source/Namdhinggo.designspace#L33) at the moment). If the text _Master_ is removed from those locations, then the build with smith fails with the message
```
source not found: 'source/instances/Namdhinggo-Regular.ufo' in bld(source=['source/instances/Namdhinggo-Regular.ufo'], target='', meths=['process_rule', 'process_taskgens', 'process_source', 'process_tempcopy'], prec=defaultdict(<class 'list'>, {}), mappings={}, features=[], path=/dev/shm/fontdev/ci/limb/fonts/namdhinggo, idx=27, rule='psfchangettfglyphnames ${SRC} .tmp/Namdhinggo-Regular.ttf Namdhinggo-Regular.ttf', shell=0, tempcopy=[/dev/shm/fontdev/ci/limb/fonts/namdhinggo/results/.tmp/Namdhinggo-Regular.ttf, /dev/shm/fontdev/ci/limb/fonts/namdhinggo/results/Namdhinggo-Regular.ttf], _name='Namdhinggo-Regular.ttf[3]psfchangettfglyphnames', late=1, posted=True) in /dev/shm/fontdev/ci/limb/fonts/namdhinggo
```

**Comment by jvgaultney** [comment]
@mhosken Can we get this fixed ASAP please?

**Comment by devosb** [comment]
Using Namdhinggo for testing, the fix that I mentioned seems to work. And the fix did not break the Namdhinggo project while the text _Master_ was still in the Designspace file. So the fix in smith can deployed with out breaking projects. Once smith is updated, then the text _Master_ can be removed, and a change in `wscript` is required.
```
cmd('psfchangettfglyphnames ${SRC} ${DEP} ${TGT}', ['source/instances/${DS:FILENAME_BASE}.ufo'])
```
needs to be
```
cmd('psfchangettfglyphnames ${SRC} ${DEP} ${TGT}', ['${source}'])
```
This type of change might be needed for other `cmd()` statements.

**Comment by devosb** [comment]
Closed by [merging](https://github.com/silnrsi/smith/commit/2413ae3c6296b3a21186d36f41178f0a36f66405) the `manifest` branch into the master `branch`, thus picking up the fix.

**Comment by mhosken** [comment]
The reason for needing to use ${source} is that with the introduction of build caching, ${source} isn't always ${DS:FILENAME} as was how things were before ${source} appeared. So if you keep using ${DS:FILENAME} you may be referring to the wrong file that hasn't been tweaked to say building an instance from a master.
