### ISSUE TITLE
smith should allow README.md in place of README.txt

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#8]
GitHub projects are strongly encouraged to include a README.md in the project root. 

smith-based font projects warn if there is no README.txt: 
   Readme file 'README.txt' not found. 

So do smith-based projects hosted on Github need both? If so, do they/should they differ in content?

MH replied:

> I agree. I have fallen foul of this in that README.txt does not have markdown interpretation applied to it. I suggest raising a bug against smith to allow it to treat README.md as if it were a README.txt, so that a project can have either.

**Comment by bobh0303** [comment]
As it turns out, it appears the message can be silenced by defining README in the wscript, e.g.:

`README='README.md'`

so maybe we don't need to do anything else (other than document it).

**Comment by bobh0303** [comment]
I have added documentation to package.asc

**Comment by bobh0303** [comment]
In subsequent discussions, we have come to a different conclusion, namely that both README.md and README.txt are useful but for different purposes: the .md is targeted at project collaborators/developers, while the .txt is targeted at users of the packaged product(s).   Thus if both .txt and .md are in the repo, **only the .txt should be included in the zip, exe, etc. packages**.  If only one of .txt and .md is in the repo, or if wscript has a README override, use that.

**Comment by jvgaultney** [comment]
Bob asked if this is correct: "If only one of .txt and .md is in the repo, or if wscript has a README override, use that." From a purely Smith perspective, yes. However in all our projects we should not have the situation where only one exists, nor should we ever override them within the wscript, so accommodating those (non-conforming) situations should not be a priority.

**Comment by bobh0303** [comment]
This seems like a simple bug for someone who knows smith -- can we get it fixed?

**Comment by devosb** [comment]
README.md in the root of the project will no longer be in user products (zip and tar), even if README.txt does not exist or there is a README override in wscript. README.md in sub-directories would still be included.
